export = Object.freeze({
    LEAVE_TABLE_ERROR: 'Leave Table Error',
    INSERT_NEW_PLAYER_ERROR: 'Insert Player In Table Error',
    WAITING_FOR_PLAYERS_ERROR: 'Waiting for Players Error',
    MATCH_MACKING_ERROR: 'Match Matching Error',
    LOCK_IN_PERIOD_ERROR: 'Lock In Period Error',
    INIT_FIRST_ROUND_ERROR: 'Initialize First Round Error',
    BOOT_COLLECTION_ERROR: 'Boot Collection Error',
    TOSS_CARD_TIMER_ERROR: 'Toss Card Timer Error',
    START_ROUND_ERROR: 'Start Round Error',
    PLAYER_FIRST_TURN_ERROR: 'Player First Turn Error',
    CARDS_SORT_ERROR: 'Card Sort Error',
    GROUP_CARDS_ERROR: 'Group Cards Error',
    END_DRAG_ERROR: 'End Drag Error',
    PICK_UP_FROM_OPEN_DECK_ERROR: 'Picking Up From Open Deck Error',
    PICK_UP_FROM_CLOSE_DECK_ERROR: 'Picking Up From Close Deck Error',
    DISCARD_CARD_ERROR: 'Discard Card Error',
    DROP_ROUND_ERROR: 'Drop Round Error',
    CHECK_WINNER_PLAYER_ERROR: 'Check winning Player error',
    USER_DICONNECTION_ERROR: 'User Disconnection Error',
    FINISHINF_TIMER_ERROR: 'Finish Timer Error',
    AUTO_DECLARE_FINISH_TIMER_ERROR: 'Auto Declare Finalizer Error',
    AUTO_DECLARE_REMAIN_TIMER_ERROR: 'Auto Declare Remain Players Error',
    DECLARE_ERROR: 'Declare Error',
    NEXT_PLAYER_CHANGE_TURN_ERROR: 'Next Player Change turn Error',
    NEXT_ROUND_CHANGE_ERROR: 'Next Round Change Error',
    RE_JOIN_PLAYER_ERROR: 'Join Player Error',
    VIEW_SCORE_BOARD_ERROR: 'View Score Board Error',
    LEAVE_TABLE_TIME_OUT_ERROR: 'Leave Table Time Out Error',
    MANUAL_SPLIT_AMOUNT_ERROR: 'Manual split amount Error',
    SPLIT_AMOUNT_ERROR: 'Split Amount Error',
    AMOUNT_SPLIT_DETAILS_ERROR: 'Amount Split Details Error',
    SHOW_OPEN_DECK_CARDS_ERROR: 'Show Open Deck Cards Error',
    INSUFFICIENT_BALANCE: `Insufficient Balance For This Table`,
    SOMETHIG_WRONG_WITH_BALANCE_ERROR: `Some reason we cann't deduct EntryFee for rejoin game Again !`,
});